// Only new production boundaries; previously passed workflows are not repeated.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mock} from './mock-github.mjs';
import {GitHubStore,appToken} from '../src/github.mjs';
import production from '../docs/production-deploy/worker.mjs';
import {sign} from '../src/security.mjs';
const ORIGIN='https://powerlifting-admin-v2-production.powerlifting-aze-482.workers.dev',BASE='a'.repeat(40),CONTENT='b'.repeat(40);
async function harness(){const h=await mock();Object.assign(h.env,{PRODUCTION_REVIEW_ONLY:'true',STAGING_ONLY:'false',GITHUB_REPOSITORY:'HafizV1/powerlifting.az',BASE_BRANCH:'main',DATA_BRANCH:'v2/content-production',ENABLE_V1_EXPORT:'false'});h.refs.set('main',BASE);h.commits.set(BASE,h.commits.get('seed'));h.refs.set('v2/content-production',CONTENT);h.commits.set(CONTENT,h.commits.get('seed'));h.store=new GitHubStore(h.env);return h;}
test('production bundle has fixed origin/repository policy, denies local/unauthenticated access and excludes E2E assets',async()=>{const bindings={PUBLIC_ORIGIN:'https://evil.example',STAGING_ONLY:'true',GITHUB_REPOSITORY:'HafizV1/powerlifting-v1-preview'};const health=await production.fetch(new Request(ORIGIN+'/api/health'),bindings);assert.equal((await health.json()).service,'powerlifting-v2-production');for(const path of ['/api/content','/api/import/baseline','/api/release/review'])assert.equal((await production.fetch(new Request(ORIGIN+path),bindings)).status,401);for(const path of ['/e2e.html','/e2e.js','/e2e-fixtures.js'])assert.equal((await production.fetch(new Request(ORIGIN+path),bindings)).status,404);assert.equal((await production.fetch(new Request(ORIGIN+'/api/auth/local',{method:'POST',headers:{Origin:ORIGIN}}),bindings)).status,404);});
test('production guard rejects preview repo, wrong base/data branch and simultaneous staging mode before API access',async()=>{const h=await harness();for(const overrides of [{GITHUB_REPOSITORY:'HafizV1/powerlifting-v1-preview'},{BASE_BRANCH:'feature/v2-admin-panel'},{DATA_BRANCH:'main'},{STAGING_ONLY:'true'}]){const env={...h.env,...overrides,FETCH:()=>{throw Error('Must not contact GitHub');}};await assert.rejects(()=>new GitHubStore(env).load(),e=>e.status===403);}assert.equal(h.writes.length,0);});
test('production release creates only a draft PR targeting main with backups; never writes main or auto-merges',async()=>{const h=await harness(),state=await h.store.load();state.collections.news.push({id:'news-test-production-guard',title:'TEST ONLY — NEVER PUBLISH',body:'Temporary mock validation',status:'published'});const r=await h.store.releaseReview(state,{login:'controlled-test'});assert.match(r.branch,/^v2\/release-production-/);assert.equal(r.reviewMode,'production');assert.equal(r.publicPublishing,false);assert.equal(h.prs[0].base,'main');assert.equal(h.prs[0].draft,true);assert.equal(h.prs[0].auto_merge,null);assert.equal(h.refs.get('main'),BASE);assert.equal(h.refs.get('v2/content-production'),CONTENT);const tree=h.writes.find(x=>x.route==='git/trees').input.tree;assert.ok(tree.some(x=>x.path.endsWith('/backup/xeberler.html')));assert.ok(!tree.some(x=>['index.html','idmancilar.html','CNAME'].includes(x.path)));});
test('production content save writes only its isolated draft branch',async()=>{const h=await harness(),state=await h.store.load();state.collections.news[0].title+=' TEST ONLY';await h.store.save(state,'news',[],[],{login:'controlled-test'});const updates=h.writes.filter(x=>x.route.startsWith('git/refs/heads/'));assert.equal(updates.length,1);assert.equal(updates[0].route,'git/refs/heads/v2/content-production');assert.equal(updates[0].input.force,false);assert.equal(h.refs.get('main'),BASE);});
test('production App resolves canonical OAuth Client ID and rejects staging App keys',async()=>{const h=await harness(),bindings={...h.env,GITHUB_CLIENT_SECRET:'production-test-secret-at-least-32-bytes',GITHUB_CLIENT_ID:'incorrect-fixture-id'};bindings.FETCH=async url=>{assert.equal(url,'https://api.github.com/app');return Response.json({id:123,slug:'powerlifting-v2-production-admin',client_id:'Iv1.production-test-client'});};const r=await production.fetch(new Request(ORIGIN+'/api/auth/github'),bindings);assert.equal(r.status,302);const target=new URL(r.headers.get('Location'));assert.equal(target.searchParams.get('client_id'),'Iv1.production-test-client');assert.equal(target.searchParams.get('redirect_uri'),ORIGIN+'/api/auth/callback');bindings.FETCH=async()=>Response.json({id:123,slug:'powerlifting-v2-staging-admin',client_id:'Iv1.staging'});assert.equal((await production.fetch(new Request(ORIGIN+'/api/auth/github'),bindings)).status,503);});
test('production installation ID is discovered server-side and token permission scope remains one repository',async()=>{const h=await harness(),baseFetch=h.env.FETCH;delete h.env.GITHUB_INSTALLATION_ID;let discovered=false;h.env.FETCH=async(url,options)=>{if(url==='https://api.github.com/repos/HafizV1/powerlifting.az/installation'){discovered=true;assert.match(options.headers.Authorization,/^Bearer ey/);return Response.json({id:456,app_id:123,repository_selection:'selected'});}return baseFetch(url,options);};assert.equal(await appToken(h.env),'installation-token-server-only');assert.ok(discovered);});
test('production and staging session signing domains are distinct even with the same hypothetical secret',async()=>{const secret='hypothetical-shared-fixture-only-at-least-32-bytes',bytes=new TextEncoder(),material=await crypto.subtle.importKey('raw',bytes.encode(secret),'HKDF',false,['deriveBits']),stage='https://powerlifting-admin-v2-staging.powerlifting-aze-482.workers.dev';const key=await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt:bytes.encode(stage),info:bytes.encode('powerlifting-v2-staging/session-signing/v1')},material,384);const stageKey=Array.from(new Uint8Array(key),b=>b.toString(16).padStart(2,'0')).join('');const token=await sign({id:'335450583',login:'fixture',csrf:'fixture',exp:Date.now()+600000},stageKey);const r=await production.fetch(new Request(ORIGIN+'/api/session',{headers:{Cookie:'__Host-pl-admin='+token}}),{GITHUB_CLIENT_SECRET:secret});assert.equal((await r.json()).user,null);});
